import { Crown, Star, Zap } from 'lucide-react'

export const plans = [
  {
    id: 'explorer',
    name: 'Explorer',
    description: 'Perfect for solo travelers',
    monthlyPrice: '$99',
    yearlyPrice: '$990',
    icon: <Star className="size-5 text-yellow-500" />,
    features: [
      { text: 'Access to 20+ destinations', included: true },
      { text: 'Basic travel planning assistance', included: true },
      { text: 'Standard accommodation options', included: true },
      { text: 'Group tour discounts (10%)', included: true },
      { text: 'Travel insurance included', included: true },
      { text: 'Email support (48hr response)', included: true },
      { text: 'Mobile travel app access', included: true },
      { text: 'Digital travel guides', included: true },
      { text: 'Priority booking', included: false },
      { text: '24/7 concierge service', included: false },
    ],
    button: {
      text: 'Get Started',
      url: '#',
    },
  },
  {
    id: 'adventurer',
    name: 'Adventurer',
    description: 'For frequent travelers',
    monthlyPrice: '$199',
    yearlyPrice: '$1990',
    icon: <Zap className="size-5 text-blue-500" />,
    popular: true,
    badge: 'Most Popular',
    features: [
      { text: 'Access to 80+ destinations worldwide', included: true },
      { text: 'Personalized itinerary planning', included: true },
      { text: 'Premium accommodation options', included: true },
      { text: 'Private tour discounts (20%)', included: true },
      { text: 'Comprehensive travel insurance', included: true },
      { text: 'Priority booking guarantee', included: true },
      { text: '24/7 travel support hotline', included: true },
      { text: 'Airport lounge access (select cities)', included: true },
      { text: 'Complimentary upgrades when available', included: true },
      { text: 'Exclusive local experiences', included: true },
      { text: 'Travel rewards program', included: true },
      { text: 'Multi-destination packages', included: true },
    ],
    button: {
      text: 'Start Free Trial',
      url: '#',
    },
  },
  {
    id: 'luxury',
    name: 'Luxury',
    description: 'Ultimate travel experience',
    monthlyPrice: '$499',
    yearlyPrice: '$4990',
    icon: <Crown className="size-5 text-purple-500" />,
    features: [
      { text: 'Everything in Adventurer', included: true },
      { text: 'Unlimited worldwide destinations', included: true },
      { text: 'Dedicated travel concierge', included: true },
      { text: 'Luxury 5-star accommodations', included: true },
      { text: 'Private jet & yacht options', included: true },
      { text: 'VIP meet & greet services', included: true },
      { text: 'Exclusive event access', included: true },
      { text: 'Personal photographer for trips', included: true },
      { text: 'Premium travel insurance (worldwide)', included: true },
      { text: 'Complimentary companion tickets', included: true },
      { text: 'Private guided tours', included: true },
      { text: 'Michelin-star dining experiences', included: true },
    ],
    button: {
      text: 'Contact Us',
      url: '#',
    },
  },
]
